config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  resources :users do
    resources :posts do
      member do
        post 'like'
        delete 'unlike'
      end
      resources :comments
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user

    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all
      can :delete, [Post, Comment], author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Associations
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  # Attributes
  attribute :text, :text

  # Callbacks
  after_create :increase_post_comments_counter
  after_destroy :decrement_post_comments_counter

  # Methods
  def increase_post_comments_counter
    post.increment!(:comments_counter)
  end

  def decrement_post_comments_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  # Associations
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  # Callbacks
  after_save :increment_post_likes_counter
  after_destroy :decrement_post_likes_counter

  # Methods
  def increment_post_likes_counter
    post.increment!(:likes_counter)
  end

  def decrement_post_likes_counter
    post.decrement!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # Associations
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  # Attributes
  attribute :title, :string
  attribute :text, :text
  attribute :comments_counter, :integer, default: 0
  attribute :likes_counter, :integer, default: 0

  # Callbacks
  after_save :increase_user_posts_counter
  after_destroy :decrease_user_posts_counter

  # Validations
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  # Methods
  def increase_user_posts_counter
    author.increment!(:posts_counter)
  end

  def decrease_user_posts_counter
    author.decrement!(:posts_counter)
  end

  def five_most_recent_comments
    comments.includes(:author).order(created_at: :asc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  # Associations
  has_many :posts, foreign_key: :author_id
  has_many :comments
  has_many :likes

  # Attributes
  attribute :name, :string
  attribute :bio, :text
  attribute :posts_counter, :integer, default: 0
  attribute :photo, :string

  # Validations
  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  # Methods
  def three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ActionController::API
  before_action :find_user_and_post

  def index
    @comments = @post.comments
    render json: @comments
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.author = @user

    if @comment.save
      render json: @comment, status: :created
    else
      render json: { error: @comment.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def find_user_and_post
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ActionController::API
  before_action :find_user

  def index
    @posts = @user.posts
    render json: @posts
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name role])
  end

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_user
  before_action :find_post
  before_action :find_comment, only: :destroy

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.author = @user # Assign the current user to the comment
    if @comment.save
      flash[:notice] = 'Comment created successfully.'
      redirect_to user_post_path(@post.author, @post)
    else
      render 'new'
    end
  end

  def destroy
    authorize! :delete, @comment

    if @comment.destroy
      flash[:notice] = 'Comment was successfully deleted.'
    else
      flash[:alert] = 'Failed to delete comment.'
    end

    redirect_to user_post_path(@user, @post)
  end

  private

  def find_user
    @user = current_user
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_user, only: %i[create index show like unlike destroy]
  before_action :find_post, only: %i[show like unlike destroy]

  def index
    page = params[:page] || 1
    per_page = 10

    @posts = Post.includes(:author)
      .includes(:comments)
      .where(author: params[:user_id])
      .order(created_at: :asc)
      .offset((page.to_i - 1) * per_page)
      .limit(per_page)

    @total_pages = (@user.posts.count.to_f / per_page).ceil
    @author = @posts.first.author unless @posts.first.nil?
  end

  def show; end

  def new
    @user = current_user
    @post = @user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = 'Post created successfully.'
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def destroy
    @post.likes.destroy_all
    @post.comments.destroy_all
    @post.destroy

    redirect_to user_posts_path(@user)
  end

  def like
    @like = @post.likes.new
    @like.author = current_user
    @like.save
    redirect_to user_post_path(@user, @post)
  end

  def unlike
    @like = @post.likes.find_by(post: @post) # Find the like
    @like&.destroy # Destroy the like if found
    redirect_to user_post_path(@user, @post)
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def find_post
    @post = @user.posts.find_by(id: params[:id])
    return unless @post.nil?

    flash[:alert] = 'Post not found, back to posts page'
    redirect_to user_posts_path(@user)
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :find_user, only: [:show]

  def index
    @users = User.includes(:posts).all
  end

  def show
    @three_recent_posts = @user.three_most_recent_posts unless @user.nil?
  end

  def new; end

  def find_user
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    # Handle the situation when the post is not found
    flash[:alert] = 'User not found, back to users page'
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<a href="<%= user_post_path(@user, @post) %>">
  <button id="back-btn">⬅</button>
</a>
<h1>Create a New Comment</h1>
<h2>Post <%= @post.id %></h2>
<h2>Current User <%= @user.name %></h2>

<%= form_with model: @comment, url: user_post_comments_path(@user, @post), local: true do |form| %>
  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Comment' %>
  </div>
<% end %>

app/views/confirmables/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/confirmables/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>

    <% if user_signed_in? %>
      <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %>
    <% else %>
      <%= link_to 'Sign In', new_user_session_path %>
      <%= link_to 'Sign Up', new_user_registration_path %>
    <% end %>
  
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<a href="<%= users_path() %>">
    <button id="back-btn">⬅</button>
</a>
<ul>
    <a href="<%= user_path(@user) %>">
        <div class="user-box">
            <%= render partial: 'shared/user_details', locals: { user: @user } %>
        </div>
    </a>
    <% @posts.each do |post|%>
        <a href="<%= user_post_path(@user, post) %>">
            <div class="user-post">
                <div class="post">
                    <h3>Post <%= raw "#" + post.id.to_s %></h3>
                    <h2><%= post.title %></h2>
                    <p><%= truncate(post.text, length: 100) %></p>
                    <div class='post-interactions'>
                        <span>Comments: <%= post.comments_counter %>,</span>
                        <span>Likes: <%= post.likes_counter %></span>
                    </div>
                </div>
                <h3>Comments:</h3>
                <% recent_comments = post.five_most_recent_comments.includes(:author) %>
                <% recent_comments.each do |comment| %>
                <div class="post-comments">
                    <span><%= comment.author.name %>:</span>
                    <span><%= comment.text %></span>
                </div>
                <% end %>
            </div>
        </a>
    <% end %>
    <a href="<%= new_user_post_path(@user) %>">
        <button id="back-btn">New Post</button>
    </a>
    <nav class="">
        <ul class="pagination justify-content-center">
            <% (1..@total_pages).each do |page| %>
                <li class="page-item"><a class="" href="/users/<%= @author.id %>/posts?page=<%= page %>"><%= page %></a></li>
            <% end %>
        </ul>
    </nav>
</ul>

app/views/posts/new.html.erb
<a href="<%= user_path(@user) %>">
  <button id="back-btn">⬅</button>
</a>
<h1>Create a New Post</h1>
<%= form_with model: [@user, @post], local: true do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Post' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<a href="<%= user_posts_path() %>">
  <button id="back-btn">⬅</button>
</a>
<h3>Post <%= "#" + @post.id.to_s %> by <%= @user.name %></h3>
<h2><%= @post.title %></h2>
<p><%= @post.text %></p>
<div class='post-interactions'>
  <span>Comments: <%= @post.comments_counter %>,</span>
  <span>Likes: <%= @post.likes_counter %></span>
</div>
<% if current_user.present? %>
  <div class="post-actions">
    <%= button_to "Like", like_user_post_path(@user, @post), method: :post, remote: true %>
    <%= button_to "Unlike", unlike_user_post_path(@user, @post), method: :delete, remote: true %>
  </div>
<% end %>
<h3>Comments:</h3>
<% @post.comments.each do |comment| %>
<div class="post-comments">
  <span><%= comment.author.name %>:</span>
  <span><%= comment.text %></span>
</div>
<% if can?(:delete, comment) %>
  <%= link_to 'Delete', user_post_comment_path(@user, @post, comment), data: { turbo_method: :delete, confirm: 'Are you sure?' } %>
<% end %>
<% end %>
<a href="<%= new_user_post_comment_path(@user, @post) %>">
  <button id="back-btn">Add a comment</button>
</a>
<% if can?(:delete, @post) %>
  <%= link_to 'Delete', user_post_path(@user, @post), data: { turbo_method: :delete, confirm: 'Are you sure?' } %>
<% end %>

app/views/shared/_user_details.html.erb
<% if user.photo.present? %>
    <div class="user-photo d-flex">
        <%= image_tag user.photo, alt: user.name, class: 'w-100' %>
    </div>
<% else %>
    <div class="user-photo placeholder">
        No photo
    </div>
<% end %>
<div class="user-details">
    <div class="user-name">
        <%= user.role %>
        <%= user.name %>
    </div>
    <div class=posts-count">
        <%= user.posts_counter %>
        <% if user.posts_counter == 1 %>
        <span>post</span>
        <% else %>
        <span>posts</span>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
  <% unless @users.nil? %>
    <% @users.each do |user| %>
      <a href="<%= user_posts_path(user) %>">
        <div class="user-box">
          <%= render partial: 'shared/user_details', locals: { user: user } %>
        </div>
      </a>
    <% end %>
  <% else %>
    <p>Please sign in or sign up to view user details.</p>
    <%= link_to 'Sign In', new_user_session_path %>
    <%= link_to 'Sign Up', new_user_registration_path %>
  <% end %>
</ul>

app/views/users/show.html.erb
<a href="<%= user_posts_path(@user) %>">
    <button id="back-btn">⬅</button>
</a>
<div class="user-box">
    <%= render partial: 'shared/user_details', locals: { user: @user } %>
</div>
<div class="bio">
    <h3>Bio</h3>
    <p>
        <%= @user.bio %>
    </p>
</div>
<% @three_recent_posts.each do |post| %>
    <a href="<%= user_post_path(@user, post) %>">
        <div class="post bio">
            <h3>Post <%= raw "#" + post.id.to_s %></h3>
            <p><%= post.text %></p>
            <div class='post-interactions'>
                <span>Comments: <%= post.comments_counter %>,</span>
                <span>Likes: <%= post.likes_counter %></span>
            </div>
        </div>
    </a>
<% end %>
<a href="<%= user_posts_path(@user) %>">
    <button id="pagination">See all posts</button>
</a>